services:
  - type: web
    name: stock-app-real
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: PORT
        value: 8080
      - key: NODE_VERSION
        value: 20
